version: "3"

services:
  ec-cube:
    build:
      context: .
      args:
        SKIP_INSTALL_SCRIPT_ON_DOCKER_BUILD: "true"
    ports:
      - 8251:80
    volumes:
      - ".:/var/www/html:cached"
      - "var:/var/www/html/var"
      - "vendor:/var/www/html/vendor"
    environment:
      APP_ENV: prod
      MAILER_URL: smtp://wheatllama8.sakura.ne.jp:587?encryption=tls&auth_mode=login&username=info@s-africa.wine&password=65z%40nnS4N54Ugcv

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eccubedb
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: secret
    volumes:
      - mysql-database:/var/lib/mysql
    ports:
      - "13306:3306"

volumes:
  var:
  vendor:
  mysql-database:
