<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\CustomerRank\Repository\CustomerRankRepository' shared autowired service.

include_once $this->targetDirs[3].'/app/Plugin/CustomerRank/Repository/CustomerRankRepository.php';

return $this->services['Plugin\\CustomerRank\\Repository\\CustomerRankRepository'] = new \Plugin\CustomerRank\Repository\CustomerRankRepository(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'});
