<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'autowired.Plugin\GmoEpsilon4\Entity\CreditAccessLog' shared autowired service.

include_once $this->targetDirs[3].'/src/Eccube/Entity/AbstractEntity.php';
include_once $this->targetDirs[3].'/app/Plugin/GmoEpsilon4/Entity/CreditAccessLog.php';

return $this->services['autowired.Plugin\\GmoEpsilon4\\Entity\\CreditAccessLog'] = new \Plugin\GmoEpsilon4\Entity\CreditAccessLog();
