<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\GmoEpsilon4\Repository\CreditBlockRepository' shared autowired service.

include_once $this->targetDirs[3].'/app/Plugin/GmoEpsilon4/Repository/CreditBlockRepository.php';

return $this->services['Plugin\\GmoEpsilon4\\Repository\\CreditBlockRepository'] = new \Plugin\GmoEpsilon4\Repository\CreditBlockRepository(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'});
