<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\CustomerRank\Service\PurchaseFlow\Processor\CustomerRankDiscountProcessor' shared autowired service.

include_once $this->targetDirs[3].'/src/Eccube/Service/PurchaseFlow/DiscountProcessor.php';
include_once $this->targetDirs[3].'/app/Plugin/CustomerRank/Service/PurchaseFlow/Processor/CustomerRankDiscountProcessor.php';

return $this->services['Plugin\\CustomerRank\\Service\\PurchaseFlow\\Processor\\CustomerRankDiscountProcessor'] = new \Plugin\CustomerRank\Service\PurchaseFlow\Processor\CustomerRankDiscountProcessor(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'});
