<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\CustomerRank\CustomerRankEvent' shared autowired service.

include_once $this->targetDirs[3].'/app/Plugin/CustomerRank/CustomerRankEvent.php';

return $this->services['Plugin\\CustomerRank\\CustomerRankEvent'] = new \Plugin\CustomerRank\CustomerRankEvent(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'}, ${($_ = isset($this->services['Eccube\\Repository\\CustomerRepository']) ? $this->services['Eccube\\Repository\\CustomerRepository'] : $this->load('getCustomerRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['Eccube\\Repository\\ProductClassRepository']) ? $this->services['Eccube\\Repository\\ProductClassRepository'] : $this->getProductClassRepositoryService()) && false ?: '_'}, ${($_ = isset($this->services['Eccube\\Service\\CartService']) ? $this->services['Eccube\\Service\\CartService'] : $this->getCartServiceService()) && false ?: '_'}, ${($_ = isset($this->services['Plugin\\CustomerRank\\Repository\\CustomerRankRepository']) ? $this->services['Plugin\\CustomerRank\\Repository\\CustomerRankRepository'] : $this->load('getCustomerRankRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['Plugin\\CustomerRank\\Repository\\CustomerPriceRepository']) ? $this->services['Plugin\\CustomerRank\\Repository\\CustomerPriceRepository'] : $this->load('getCustomerPriceRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['Plugin\\CustomerRank\\Service\\CustomerRankService']) ? $this->services['Plugin\\CustomerRank\\Service\\CustomerRankService'] : $this->load('getCustomerRankServiceService.php')) && false ?: '_'});
