<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\CustomerRank\Service\PurchaseFlow\Processor\CustomerRankPointProcessor' shared autowired service.

include_once $this->targetDirs[3].'/src/Eccube/Service/PurchaseFlow/ValidatorTrait.php';
include_once $this->targetDirs[3].'/src/Eccube/Service/PurchaseFlow/ItemHolderPostValidator.php';
include_once $this->targetDirs[3].'/app/Plugin/CustomerRank/Service/PurchaseFlow/Processor/CustomerRankPointProcessor.php';

return $this->services['Plugin\\CustomerRank\\Service\\PurchaseFlow\\Processor\\CustomerRankPointProcessor'] = new \Plugin\CustomerRank\Service\PurchaseFlow\Processor\CustomerRankPointProcessor(${($_ = isset($this->services['Eccube\\Repository\\BaseInfoRepository']) ? $this->services['Eccube\\Repository\\BaseInfoRepository'] : $this->getBaseInfoRepositoryService()) && false ?: '_'}, ${($_ = isset($this->services['Plugin\\CustomerRank\\Service\\CustomerRankService']) ? $this->services['Plugin\\CustomerRank\\Service\\CustomerRankService'] : $this->load('getCustomerRankServiceService.php')) && false ?: '_'});
