<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'autowired.Eccube\Entity\Layout' shared autowired service.

include_once $this->targetDirs[3].'/src/Eccube/Entity/AbstractEntity.php';
include_once $this->targetDirs[3].'/app/Plugin/SSProductDetailPage/Entity/LayoutTrait.php';
include_once $this->targetDirs[3].'/app/proxy/entity/src/Eccube/Entity/Layout.php';

return $this->services['autowired.Eccube\\Entity\\Layout'] = new \Eccube\Entity\Layout();
