<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\CustomerRank\Service\PurchaseFlow\Processor\PriceChangeProcessor' shared autowired service.

include_once $this->targetDirs[3].'/src/Eccube/Service/PurchaseFlow/ValidatorTrait.php';
include_once $this->targetDirs[3].'/src/Eccube/Service/PurchaseFlow/ItemValidator.php';
include_once $this->targetDirs[3].'/app/Plugin/CustomerRank/Service/PurchaseFlow/Processor/PriceChangeProcessor.php';

return $this->services['Plugin\\CustomerRank\\Service\\PurchaseFlow\\Processor\\PriceChangeProcessor'] = new \Plugin\CustomerRank\Service\PurchaseFlow\Processor\PriceChangeProcessor(${($_ = isset($this->services['Plugin\\CustomerRank\\Repository\\CustomerPriceRepository']) ? $this->services['Plugin\\CustomerRank\\Repository\\CustomerPriceRepository'] : $this->load('getCustomerPriceRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['Plugin\\CustomerRank\\Service\\CustomerRankService']) ? $this->services['Plugin\\CustomerRank\\Service\\CustomerRankService'] : $this->load('getCustomerRankServiceService.php')) && false ?: '_'}, ${($_ = isset($this->services['Eccube\\Service\\TaxRuleService']) ? $this->services['Eccube\\Service\\TaxRuleService'] : $this->load('getTaxRuleServiceService.php')) && false ?: '_'});
