<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\SSProductDetailPage\Repository\ProductLayoutRepository' shared autowired service.

include_once $this->targetDirs[3].'/app/Plugin/SSProductDetailPage/Repository/ProductLayoutRepository.php';

return $this->services['Plugin\\SSProductDetailPage\\Repository\\ProductLayoutRepository'] = new \Plugin\SSProductDetailPage\Repository\ProductLayoutRepository(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'});
