<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\Recommend4\Repository\RecommendProductRepository' shared autowired service.

include_once $this->targetDirs[3].'/app/Plugin/Recommend4/Repository/RecommendProductRepository.php';

return $this->services['Plugin\\Recommend4\\Repository\\RecommendProductRepository'] = new \Plugin\Recommend4\Repository\RecommendProductRepository(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'});
