<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'autowired.Plugin\Recommend4\Entity\RecommendProduct' shared autowired service.

include_once $this->targetDirs[3].'/src/Eccube/Entity/AbstractEntity.php';
include_once $this->targetDirs[3].'/app/Plugin/Recommend4/Entity/RecommendProduct.php';

return $this->services['autowired.Plugin\\Recommend4\\Entity\\RecommendProduct'] = new \Plugin\Recommend4\Entity\RecommendProduct();
