<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\SitemapXmlGenerator\Form\Type\Admin\SitemapSettingType' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractType.php';
include_once $this->targetDirs[3].'/app/Plugin/SitemapXmlGenerator/Form/Type/Admin/SitemapSettingType.php';

return $this->services['Plugin\\SitemapXmlGenerator\\Form\\Type\\Admin\\SitemapSettingType'] = new \Plugin\SitemapXmlGenerator\Form\Type\Admin\SitemapSettingType();
