<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\SSProductDetailPage\TemplateLayoutListener' shared autowired service.

include_once $this->targetDirs[3].'/app/Plugin/SSProductDetailPage/TemplateLayoutListener.php';

return $this->services['Plugin\\SSProductDetailPage\\TemplateLayoutListener'] = new \Plugin\SSProductDetailPage\TemplateLayoutListener(${($_ = isset($this->services['twig']) ? $this->services['twig'] : $this->getTwigService()) && false ?: '_'}, ${($_ = isset($this->services['Eccube\\Request\\Context']) ? $this->services['Eccube\\Request\\Context'] : $this->getContextService()) && false ?: '_'}, ${($_ = isset($this->services['mobile_detect.mobile_detector.default']) ? $this->services['mobile_detect.mobile_detector.default'] : ($this->services['mobile_detect.mobile_detector.default'] = new \SunCat\MobileDetectBundle\DeviceDetector\MobileDetector())) && false ?: '_'}, ${($_ = isset($this->services['Eccube\\Repository\\LayoutRepository']) ? $this->services['Eccube\\Repository\\LayoutRepository'] : $this->getLayoutRepositoryService()) && false ?: '_'});
