<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\CustomerRank\Form\Extension\AdminCustomerExtension' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeExtensionInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractTypeExtension.php';
include_once $this->targetDirs[3].'/app/Plugin/CustomerRank/Form/Extension/AdminCustomerExtension.php';

return $this->services['Plugin\\CustomerRank\\Form\\Extension\\AdminCustomerExtension'] = new \Plugin\CustomerRank\Form\Extension\AdminCustomerExtension();
