<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\CustomerRank\Form\Type\Admin\CustomerRankType' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractType.php';
include_once $this->targetDirs[3].'/app/Plugin/CustomerRank/Form/Type/Admin/CustomerRankType.php';

return $this->services['Plugin\\CustomerRank\\Form\\Type\\Admin\\CustomerRankType'] = new \Plugin\CustomerRank\Form\Type\Admin\CustomerRankType();
