<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'customerrank.api.allow_list' shared service.

return $this->services['customerrank.api.allow_list'] = new \ArrayObject(['Eccube\\Entity\\Customer' => [0 => 'check_date', 1 => 'CustomerRank'], 'Plugin\\CustomerRank\\Entity\\CustomerRank' => [0 => 'id', 1 => 'name', 2 => 'discount_rate', 3 => 'discount_value', 4 => 'point_rate', 5 => 'delivery_free_condition', 6 => 'cond_amount', 7 => 'cond_buytimes', 8 => 'initial_flg', 9 => 'fixed_flg', 10 => 'priority'], 'Eccube\\Entity\\ProductClass' => [0 => 'CustomerPrices'], 'Plugin\\CustomerRank\\Entity\\CustomerPrice' => [0 => 'price', 1 => 'CustomerRank', 2 => 'ProductClass'], 'Eccube\\Entity\\Order' => [0 => 'customer_rank_id', 1 => 'customer_rank_name']]);
