<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\GmoEpsilon4\Form\Extension\ConveniExtention' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeExtensionInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractTypeExtension.php';
include_once $this->targetDirs[3].'/app/Plugin/GmoEpsilon4/Form/Extension/ConveniExtention.php';

return $this->services['Plugin\\GmoEpsilon4\\Form\\Extension\\ConveniExtention'] = new \Plugin\GmoEpsilon4\Form\Extension\ConveniExtention(${($_ = isset($this->services['Eccube\\Common\\EccubeConfig']) ? $this->services['Eccube\\Common\\EccubeConfig'] : ($this->services['Eccube\\Common\\EccubeConfig'] = new \Eccube\Common\EccubeConfig($this))) && false ?: '_'}, ${($_ = isset($this->services['Eccube\\Repository\\PaymentRepository']) ? $this->services['Eccube\\Repository\\PaymentRepository'] : $this->load('getPaymentRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['Plugin\\GmoEpsilon4\\Repository\\ConfigRepository']) ? $this->services['Plugin\\GmoEpsilon4\\Repository\\ConfigRepository'] : $this->load('getConfigRepository2Service.php')) && false ?: '_'});
