<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\TaxManagement\Event' shared autowired service.

include_once $this->targetDirs[3].'/app/Plugin/TaxManagement/Event.php';
include_once $this->targetDirs[3].'/vendor/pimple/pimple/lib/Pimple.php';
include_once $this->targetDirs[3].'/src/Eccube/Application.php';

return $this->services['Plugin\\TaxManagement\\Event'] = new \Plugin\TaxManagement\Event($this, ${($_ = isset($this->services['Plugin\\TaxManagement\\Repository\\ConfigRepository']) ? $this->services['Plugin\\TaxManagement\\Repository\\ConfigRepository'] : $this->load('getConfigRepository3Service.php')) && false ?: '_'}, new \Eccube\Application());
