<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\SSProductDetailPage\Form\Extension\ProductTypeExtension' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeExtensionInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractTypeExtension.php';
include_once $this->targetDirs[3].'/app/Plugin/SSProductDetailPage/Form/Extension/ProductTypeExtension.php';

return $this->services['Plugin\\SSProductDetailPage\\Form\\Extension\\ProductTypeExtension'] = new \Plugin\SSProductDetailPage\Form\Extension\ProductTypeExtension(${($_ = isset($this->services['Eccube\\Repository\\Master\\DeviceTypeRepository']) ? $this->services['Eccube\\Repository\\Master\\DeviceTypeRepository'] : $this->getDeviceTypeRepositoryService()) && false ?: '_'});
