<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\SitemapXmlGenerator\Repository\SitemapXmlRepository' shared autowired service.

include_once $this->targetDirs[3].'/app/Plugin/SitemapXmlGenerator/Repository/SitemapXmlRepository.php';

return $this->services['Plugin\\SitemapXmlGenerator\\Repository\\SitemapXmlRepository'] = new \Plugin\SitemapXmlGenerator\Repository\SitemapXmlRepository(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'}, ${($_ = isset($this->services['Eccube\\Common\\EccubeConfig']) ? $this->services['Eccube\\Common\\EccubeConfig'] : ($this->services['Eccube\\Common\\EccubeConfig'] = new \Eccube\Common\EccubeConfig($this))) && false ?: '_'});
