<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.inoep0i' shared service.

return $this->services['service_locator.inoep0i'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['RecommendProduct' => function () {
    $f = function (\Plugin\Recommend4\Entity\RecommendProduct $v) { return $v; }; return $f(${($_ = isset($this->services['autowired.Plugin\\Recommend4\\Entity\\RecommendProduct']) ? $this->services['autowired.Plugin\\Recommend4\\Entity\\RecommendProduct'] : ($this->services['autowired.Plugin\\Recommend4\\Entity\\RecommendProduct'] = new \Plugin\Recommend4\Entity\RecommendProduct())) && false ?: '_'});
}]);
