<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3btpcyx\EccubeProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3btpcyx/EccubeProdProjectContainer.php') {
    touch(__DIR__.'/Container3btpcyx.legacy');

    return;
}

if (!\class_exists(EccubeProdProjectContainer::class, false)) {
    \class_alias(\Container3btpcyx\EccubeProdProjectContainer::class, EccubeProdProjectContainer::class, false);
}

return new \Container3btpcyx\EccubeProdProjectContainer([
    'container.build_hash' => '3btpcyx',
    'container.build_id' => 'd8b9ef91',
    'container.build_time' => 1691661405,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3btpcyx');
