<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\CategoryExtensionB\CategoryExtensionBEvent' shared autowired service.

include_once $this->targetDirs[3].'/app/Plugin/CategoryExtensionB/CategoryExtensionBEvent.php';

return $this->services['Plugin\\CategoryExtensionB\\CategoryExtensionBEvent'] = new \Plugin\CategoryExtensionB\CategoryExtensionBEvent();
