<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\SSProductDetailPage\SSProductDetailPageEvent' shared autowired service.

include_once $this->targetDirs[3].'/app/Plugin/SSProductDetailPage/SSProductDetailPageEvent.php';

return $this->services['Plugin\\SSProductDetailPage\\SSProductDetailPageEvent'] = new \Plugin\SSProductDetailPage\SSProductDetailPageEvent(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'}, ${($_ = isset($this->services['Plugin\\SSProductDetailPage\\Repository\\ProductLayoutRepository']) ? $this->services['Plugin\\SSProductDetailPage\\Repository\\ProductLayoutRepository'] : $this->load('getProductLayoutRepositoryService.php')) && false ?: '_'});
