<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWrrkusj\EccubeDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWrrkusj/EccubeDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWrrkusj.legacy');

    return;
}

if (!\class_exists(EccubeDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWrrkusj\EccubeDevDebugProjectContainer::class, EccubeDevDebugProjectContainer::class, false);
}

return new \ContainerWrrkusj\EccubeDevDebugProjectContainer([
    'container.build_hash' => 'Wrrkusj',
    'container.build_id' => '93f43d65',
    'container.build_time' => 1611304205,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWrrkusj');
