<?php

namespace Proxies\__CG__\Plugin\SitemapXmlGenerator\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class SitemapSetting extends \Plugin\SitemapXmlGenerator\Entity\SitemapSetting implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Plugin\\SitemapXmlGenerator\\Entity\\SitemapSetting' . "\0" . 'id', '' . "\0" . 'Plugin\\SitemapXmlGenerator\\Entity\\SitemapSetting' . "\0" . 'lastmodAvailed', '' . "\0" . 'Plugin\\SitemapXmlGenerator\\Entity\\SitemapSetting' . "\0" . 'changefreq', '' . "\0" . 'Plugin\\SitemapXmlGenerator\\Entity\\SitemapSetting' . "\0" . 'priorityAvailed', '' . "\0" . 'Plugin\\SitemapXmlGenerator\\Entity\\SitemapSetting' . "\0" . 'excludedDirectories', '' . "\0" . 'Plugin\\SitemapXmlGenerator\\Entity\\SitemapSetting' . "\0" . 'createDate', '' . "\0" . 'Plugin\\SitemapXmlGenerator\\Entity\\SitemapSetting' . "\0" . 'updateDate', '' . "\0" . 'Plugin\\SitemapXmlGenerator\\Entity\\SitemapSetting' . "\0" . 'discriminatorType'];
        }

        return ['__isInitialized__', '' . "\0" . 'Plugin\\SitemapXmlGenerator\\Entity\\SitemapSetting' . "\0" . 'id', '' . "\0" . 'Plugin\\SitemapXmlGenerator\\Entity\\SitemapSetting' . "\0" . 'lastmodAvailed', '' . "\0" . 'Plugin\\SitemapXmlGenerator\\Entity\\SitemapSetting' . "\0" . 'changefreq', '' . "\0" . 'Plugin\\SitemapXmlGenerator\\Entity\\SitemapSetting' . "\0" . 'priorityAvailed', '' . "\0" . 'Plugin\\SitemapXmlGenerator\\Entity\\SitemapSetting' . "\0" . 'excludedDirectories', '' . "\0" . 'Plugin\\SitemapXmlGenerator\\Entity\\SitemapSetting' . "\0" . 'createDate', '' . "\0" . 'Plugin\\SitemapXmlGenerator\\Entity\\SitemapSetting' . "\0" . 'updateDate', '' . "\0" . 'Plugin\\SitemapXmlGenerator\\Entity\\SitemapSetting' . "\0" . 'discriminatorType'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (SitemapSetting $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastmodAvailed($lastmodAvailed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastmodAvailed', [$lastmodAvailed]);

        return parent::setLastmodAvailed($lastmodAvailed);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastmodAvailed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastmodAvailed', []);

        return parent::getLastmodAvailed();
    }

    /**
     * {@inheritDoc}
     */
    public function setChangefreq($changefreq)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChangefreq', [$changefreq]);

        return parent::setChangefreq($changefreq);
    }

    /**
     * {@inheritDoc}
     */
    public function getChangefreq()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChangefreq', []);

        return parent::getChangefreq();
    }

    /**
     * {@inheritDoc}
     */
    public function setPriorityAvailed($priorityAvailed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPriorityAvailed', [$priorityAvailed]);

        return parent::setPriorityAvailed($priorityAvailed);
    }

    /**
     * {@inheritDoc}
     */
    public function getPriorityAvailed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPriorityAvailed', []);

        return parent::getPriorityAvailed();
    }

    /**
     * {@inheritDoc}
     */
    public function setExcludedDirectories($excludedDirectories = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExcludedDirectories', [$excludedDirectories]);

        return parent::setExcludedDirectories($excludedDirectories);
    }

    /**
     * {@inheritDoc}
     */
    public function getExcludedDirectories()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExcludedDirectories', []);

        return parent::getExcludedDirectories();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreateDate($createDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreateDate', [$createDate]);

        return parent::setCreateDate($createDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreateDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreateDate', []);

        return parent::getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdateDate($updateDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdateDate', [$updateDate]);

        return parent::setUpdateDate($updateDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdateDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdateDate', []);

        return parent::getUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiscriminatorType($discriminatorType = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiscriminatorType', [$discriminatorType]);

        return parent::setDiscriminatorType($discriminatorType);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiscriminatorType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiscriminatorType', []);

        return parent::getDiscriminatorType();
    }

}
